### ISSUE TITLE
socket.error crashes TxMqttThread

### ISSUE THREAD

**Issue by twatteyne** [openwsn-berkeley/argus#13]
TxMqttThread crashes on the Argus probe, causing probe to stop publishing.

```
=============================================================
Wed, 04 Jan 2017 11:37:06 UTC

CRASH in Thread TxMqttThread!

=== exception type ===
<class 'socket.error'>

=== traceback ===
Traceback (most recent call last):
  File "C:\Users\Administrateur\Desktop\argus-REL-1.0.0.0\ArgusProbe_Beamlogic.py", line 255, in run
    port         = self.MQTT_BROKER_PORT,
  File "C:\Users\Administrateur\AppData\Roaming\Python\Python27\site-packages\paho\mqtt\publish.py", line 174, in multiple
    client.connect(hostname, port, keepalive)
  File "C:\Users\Administrateur\AppData\Roaming\Python\Python27\site-packages\paho\mqtt\client.py", line 686, in connect
    return self.reconnect()
  File "C:\Users\Administrateur\AppData\Roaming\Python\Python27\site-packages\paho\mqtt\client.py", line 808, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "C:\Python27\lib\socket.py", line 575, in create_connection
    raise err
error: [Errno 10053] Une connexion Útablie a ÚtÚ abandonnÚe par un logiciel de votre ordinateur h¶te
```

**Comment by twatteyne** [comment]
The Win computer the broker is running on at Inria-Paris goes to sleep after a couple of hours.
I believe the crash happened I revived it 10 min ago (around `Wed, 04 Jan 2017 11:37:06 UTC`).
I can fix the bug, but it should only happen when Windows goes to sleep.

**Comment by twatteyne** [comment]
I confirm that the computer was set to go to sleep after 30min of inactivity. Changed that.

**Comment by twatteyne** [comment]
I released https://github.com/openwsn-berkeley/argus/releases/tag/REL-1.0.1.0, which contains a fix to print a `WARNING` message when the probe cannot open a socket connected to the broker. Shouldn't happen normally though. That's what's now running in the Inria EVA lab.
