### ISSUE TITLE
Argus client crashes when starts on Windows

### ISSUE THREAD

**Issue by changtengfei** [openwsn-berkeley/argus#30]
When run ArguClien.py, I got following error

<code>
=============================================================
Thu, 04 Oct 2018 13:18:43 UTC

CRASH in Thread main!

=== exception type ===
<type 'exceptions.WindowsError'>

=== traceback ===
Traceback (most recent call last):
  File "C:\Users\Tengfei\Desktop\argus\ArgusClient.py", line 332, in main
    proc                 = subprocess.Popen(wireshark_cmd)
  File "C:\Python27\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 740] The requested operation requires elevation
</code>

**Comment by changtengfei** [comment]
@keomabrun can you try the branch, #30. works for you? I added a fix in that branch.

**Comment by twatteyne** [comment]
The requested operation requires elevation
Means
The requested operation requires elevation

Run as admin

**Comment by changtengfei** [comment]
For windows, it will ask for run admin with a window prompt up. The current code does't allow the prompt up windows make it crash. The fix is to allow this prompt up windows with `shell=True` in the `subprocess.POpen()` function.
